from gensim.models import Word2Vec
from gensim.utils import simple_preprocess
from annoy import AnnoyIndex
import numpy as np

# Sample scientific texts
texts = [
    "Genetics is a branch of biology concerned with the study of genes, genetic variation, and heredity in organisms.",
    "The theory of relativity is a scientific theory of the relationship between space and time.",
    "Quantum mechanics is a fundamental theory in physics that provides a description of physical properties at the scale of atoms and subatomic particles.",
    "The standard model of particle physics is a theory concerning the electromagnetic, weak, and strong nuclear forces.",
    "Neuroscience is the scientific study of the nervous system, aiming to understand how the brain and its components work.",
    "Genetics is a branch of biology concerned with the study of genes, genetic variation, and heredity in organisms.",
    "DNA is the molecule that carries genetic instructions used in the growth, development, functioning, and reproduction of all living organisms.",
    "The human brain consists of approximately 86 billion neurons that process and transmit information through electrical and chemical signals.",
    "Photosynthesis is the process by which plants, algae, and some bacteria convert light energy into chemical energy.",
    "The Earth's atmosphere is composed of 78% nitrogen, 21% oxygen, and traces of other gases like argon and carbon dioxide.",
    "Water is a universal solvent due to its polarity and ability to dissolve many different substances.",
    "Evolution by natural selection is the process through which species adapt to their environment over time.",
    "Black holes are regions in space where the gravitational pull is so strong that not even light can escape.",
    "The mitochondrion is known as the powerhouse of the cell because it generates the cell's energy through ATP.",
    "The periodic table organizes elements by increasing atomic number and groups them based on similar chemical properties.",
    "Einstein's equation E=mc^2 shows that energy and mass are interchangeable.",
    "Protons and neutrons, found in the nucleus of an atom, are composed of smaller particles called quarks.",
    "The speed of light in a vacuum is approximately 299,792 kilometers per second.",
    "Carbon, hydrogen, oxygen, and nitrogen are the four most abundant elements in living organisms.",
    "The Doppler effect explains how the frequency of sound or light waves changes relative to the observer's position.",
    "Fossils are the preserved remains or traces of organisms from the distant past, often found in sedimentary rock.",
    "A neuron transmits information to other cells through synapses, which are small gaps between the nerve terminals and the dendrites of the next cell.",
    "The sun is composed mainly of hydrogen and helium and generates energy through nuclear fusion.",
    "Earth's magnetic field is generated by the movement of molten iron in its outer core.",
    "The human genome contains about 3 billion base pairs of DNA.",
    "Enzymes are proteins that act as biological catalysts, speeding up chemical reactions in cells.",
    "A galaxy is a massive, gravitationally bound system that consists of stars, stellar remnants, interstellar gas, dust, and dark matter.",
    "Superconductors are materials that can conduct electricity without resistance when cooled to critical temperatures.",
    "In classical mechanics, Newton's first law states that an object in motion will stay in motion unless acted upon by an external force.",
    "The double helix structure of DNA was discovered by James Watson and Francis Crick in 1953.",
    "Plate tectonics is the theory explaining the movement of the Earth's lithosphere, which is divided into tectonic plates.",
    "Electrons orbit the nucleus of an atom in regions called electron shells or energy levels.",
    "Osmosis is the movement of water molecules through a semipermeable membrane from a region of low solute concentration to high solute concentration.",
    "Entropy is a measure of the disorder or randomness in a system, as described by the second law of thermodynamics.",
    "An ecosystem is a community of living organisms interacting with their physical environment.",
    "Newton's law of universal gravitation states that every mass attracts every other mass with a force proportional to their masses and inversely proportional to the square of the distance between them.",
    "Light exhibits properties of both waves and particles, a concept known as wave-particle duality.",
    "The Hubble Space Telescope has provided some of the most detailed images of distant galaxies and nebulae.",
    "The Earth's orbit around the sun is elliptical, not a perfect circle.",
    "Matter exists in four fundamental states: solid, liquid, gas, and plasma.",
    "The chemical symbol for gold is Au, which comes from its Latin name 'aurum'.",
    "The greenhouse effect is a natural process by which certain gases in Earth's atmosphere trap heat, keeping the planet warm enough to support life.",
    "The largest organ in the human body is the skin.",
    "The Richter scale measures the magnitude of earthquakes, with each whole number representing a tenfold increase in amplitude.",
    "Mendel's laws of inheritance describe how traits are passed from parents to offspring through genes.",
    "Viruses are acellular organisms that require a host cell to replicate.",
    "Antibiotics are used to treat bacterial infections but are ineffective against viruses.",
    "CRISPR is a technology used for editing genes by precisely cutting DNA and allowing natural repair mechanisms to make changes.",
    "Chlorophyll is the pigment in plants that absorbs sunlight for photosynthesis.",
    "Mars has the largest volcano in the solar system, Olympus Mons.",
    "Vaccines work by stimulating the immune system to recognize and fight specific pathogens.",
    "The ozone layer in Earth's stratosphere absorbs most of the sun's harmful ultraviolet radiation.",
    "In physics, work is done when a force applied to an object causes displacement in the direction of the force.",
    "Chemical bonds between atoms can be classified into covalent, ionic, and metallic bonds.",
    "The cerebrum is the largest part of the human brain, responsible for voluntary actions, speech, thought, and memory.",
    "Helium is the second most abundant element in the universe, primarily formed during the Big Bang.",
    "The cell membrane is a selectively permeable barrier that controls the movement of substances into and out of the cell.",
    "A light-year is the distance light travels in one year, about 5.88 trillion miles (9.46 trillion kilometers).",
    "The Milky Way is a barred spiral galaxy that contains our solar system.",
    "Tides on Earth are primarily caused by the gravitational pull of the moon and, to a lesser extent, the sun.",
    "Hydrogen is the lightest and most abundant element in the universe.",
    "RNA is a nucleic acid that plays a crucial role in coding, decoding, regulation, and expression of genes.",
    "Nanotechnology is the manipulation of matter on an atomic, molecular, and supramolecular scale.",
    "Dark matter makes up about 27% of the universe, yet it cannot be observed directly with existing instruments.",
    "The human body's circulatory system transports blood, nutrients, and oxygen to cells while removing waste products.",
    "The pH scale measures the acidity or basicity of a substance, with a pH of 7 being neutral.",
    "The International Space Station orbits Earth at an average altitude of approximately 400 kilometers (250 miles).",
    "The scientific method involves observation, hypothesis, experimentation, and conclusion to investigate phenomena.",
    "Chemical reactions involve the rearrangement of atoms to form new substances.",
    "DNA replication is the process by which a DNA molecule makes an exact copy of itself.",
    "Newton's second law of motion states that the force on an object is equal to its mass times its acceleration (F = ma).",
    "The endoplasmic reticulum (ER) is an organelle in eukaryotic cells that aids in protein and lipid synthesis.",
    "Glaciers are large masses of ice that move slowly over land, reshaping the Earth's surface.",
    "Meteorites are fragments of asteroids or comets that survive their journey through the atmosphere and land on Earth's surface.",
    "Friction is a force that opposes the relative motion of two surfaces in contact.",
    "The electromagnetic spectrum includes radio waves, microwaves, infrared, visible light, ultraviolet, X-rays, and gamma rays.",
    "Paleontology is the study of the history of life on Earth through the examination of plant and animal fossils.",
    "Human chromosomes are thread-like structures made of DNA and proteins that carry genetic information.",
    "The troposphere is the lowest layer of Earth's atmosphere, where most weather phenomena occur.",
    "Comets are composed of ice, dust, and rock, and develop a tail when they approach the sun.",
    "Bioluminescence is the production and emission of light by living organisms, such as fireflies and certain deep-sea creatures.",
    "Sound waves travel through different media at different speeds; they travel fastest through solids and slowest through gases.",
    "The half-life of a radioactive substance is the time it takes for half of the radioactive atoms in a sample to decay.",
    "Gamma radiation is a high-energy form of electromagnetic radiation emitted by radioactive atoms and in certain nuclear reactions.",
    "The pancreas produces insulin, a hormone that regulates blood sugar levels.",
    "Endothermic reactions absorb heat from their surroundings, while exothermic reactions release heat."
]


# Tokenize and preprocess texts
def preprocess(text):
    return simple_preprocess(text)

# Build Word2Vec model
sentences = [preprocess(text) for text in texts]
model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, sg=0)

# Create Annoy index
vector_size = model.vector_size
index = AnnoyIndex(vector_size, 'angular')

# Add vectors to Annoy index
for i, text in enumerate(texts):
    # Create a vector for the whole document by averaging word vectors
    words = preprocess(text)
    word_vectors = [model.wv[word] for word in words if word in model.wv]
    if word_vectors:
        doc_vector = np.mean(word_vectors, axis=0)
        index.add_item(i, doc_vector)

index.build(10)  # Build index with 10 trees

# Perform a similarity search
def find_similar(text, k=2):
    words = preprocess(text)
    word_vectors = [model.wv[word] for word in words if word in model.wv]
    if word_vectors:
        query_vector = np.mean(word_vectors, axis=0)
        return index.get_nns_by_vector(query_vector, k)

# Example search
query_text = "Quantum physics and particle theory"
nearest_neighbors = find_similar(query_text)

print("Nearest neighbors:", nearest_neighbors)
for i in nearest_neighbors:
    print(f"Text: {texts[i]}")
